
package view;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.*;

public class Login_Form extends javax.swing.JFrame {

    Investor investor = null;
    User user;
    Admin admin;
    
    ArrayList<User> listUser;
    Connection con = Database.getConnection();
    public Login_Form() throws Exception {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginForm = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        usrLabel = new javax.swing.JLabel();
        usrInput = new javax.swing.JTextField();
        pwdLabel = new javax.swing.JLabel();
        pwdInput = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        forgotPwd = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        registerLink = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(48, 48, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        loginForm.setBackground(new java.awt.Color(64, 64, 64));

        loginLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(231, 231, 231));
        loginLabel.setText("LOGIN");

        usrLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usrLabel.setForeground(new java.awt.Color(231, 231, 231));
        usrLabel.setText("Username");

        pwdLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwdLabel.setForeground(new java.awt.Color(231, 231, 231));
        pwdLabel.setText("Password");

        loginButton.setBackground(new java.awt.Color(242, 123, 53));
        loginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(231, 231, 231));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        forgotPwd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        forgotPwd.setForeground(new java.awt.Color(81, 132, 234));
        forgotPwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotPwd.setText("Forgot Password?");
        forgotPwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPwdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginFormLayout = new javax.swing.GroupLayout(loginForm);
        loginForm.setLayout(loginFormLayout);
        loginFormLayout.setHorizontalGroup(
            loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFormLayout.createSequentialGroup()
                .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginFormLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(loginLabel))
                    .addGroup(loginFormLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usrLabel)
                            .addComponent(usrInput)
                            .addComponent(pwdLabel)
                            .addComponent(pwdInput, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)))
                    .addGroup(loginFormLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(forgotPwd, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        loginFormLayout.setVerticalGroup(
            loginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFormLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(loginLabel)
                .addGap(27, 27, 27)
                .addComponent(usrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usrInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pwdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(forgotPwd)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        registerLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(231, 231, 231));
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("Belum punya akun?");

        registerLink.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        registerLink.setForeground(new java.awt.Color(81, 132, 234));
        registerLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLink.setText("Sign Up");
        registerLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLinkMouseClicked(evt);
            }
        });

        logo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logo1.setForeground(new java.awt.Color(231, 231, 231));
        logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(434, Short.MAX_VALUE)
                .addComponent(loginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(496, 496, 496))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(518, 518, 518)
                        .addComponent(registerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerLink)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerLabel)
                    .addComponent(registerLink))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLinkMouseClicked
        try {
            // TODO add your handling code here:
            new Register_Form().setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_registerLinkMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        if (usrInput.getText().equals("") || pwdInput.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Field can't be empty!");
        } else {
            try {
                PreparedStatement st = con.prepareStatement("SELECT * FROM user WHERE username = '"+usrInput.getText()+"' AND password = '"+pwdInput.getText()+"';");
                ResultSet rs = st.executeQuery();
                if (!rs.next()){
                    JOptionPane.showMessageDialog(this, "User tidak ditemukan");
                    try {
                        new Dashboard_Guest().setVisible(true);
                        this.setVisible(false);
                    } catch (Exception ex) {
                        Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                try {
                    if(User.showRole(usrInput.getText()).equals("investor")){
                        User user = new User(rs.getString(2),rs.getString(3), rs.getString(4));
                        Investor inv = new Investor(rs.getString(2),rs.getString(3), rs.getString(4));
                        //JOptionPane.showMessageDialog(this, "Welcome, '"+user.getNama()+"'");
                        new Dashboard_Investor(user).setVisible(true);
                        this.setVisible(false);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    if(User.showRole(usrInput.getText()).equals("admin")){
                        User user = new User(rs.getString(2),rs.getString(3), rs.getString(4));
                        Admin adm = new Admin(rs.getString(2),rs.getString(3), rs.getString(4));
                        //JOptionPane.showMessageDialog(this, "Welcome, '"+user.getNama()+"'");
                        new Dashboard_Admin(user).setVisible(true);
                        this.setVisible(false);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void forgotPwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPwdMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new ForgotPassword_Form().setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_forgotPwdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException, Exception{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Database db = new Database();
        db.getConnection();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login_Form().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forgotPwd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginForm;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel logo1;
    private javax.swing.JTextField pwdInput;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JLabel registerLink;
    private javax.swing.JTextField usrInput;
    private javax.swing.JLabel usrLabel;
    // End of variables declaration//GEN-END:variables
}
