package view;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.*;
public class TopUpConfirmation_Investor extends javax.swing.JFrame {
    User usr;
    int jumlah;
    public TopUpConfirmation_Investor(User usr, int jumlah) throws Exception{
        this.usr = usr;
        this.jumlah = jumlah;
        
        initComponents();
        totalAmount.setText("Rp. "+this.jumlah);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        confForm7 = new javax.swing.JPanel();
        topupLabel = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        totalAmount = new javax.swing.JLabel();
        qris = new javax.swing.JLabel();
        pwdLabel7 = new javax.swing.JLabel();
        pwdInput7 = new javax.swing.JTextField();
        topupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel8.setBackground(new java.awt.Color(48, 48, 48));
        jPanel8.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel8.setMinimumSize(new java.awt.Dimension(1280, 720));

        confForm7.setBackground(new java.awt.Color(64, 64, 64));
        confForm7.setMaximumSize(new java.awt.Dimension(350, 493));
        confForm7.setMinimumSize(new java.awt.Dimension(350, 493));

        topupLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        topupLabel.setForeground(new java.awt.Color(231, 231, 231));
        topupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topupLabel.setText("Top Up");

        totalAmountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalAmountLabel.setForeground(new java.awt.Color(231, 231, 231));
        totalAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAmountLabel.setText("Total Amount");

        totalAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalAmount.setForeground(new java.awt.Color(231, 231, 231));
        totalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAmount.setText("Rp xxx.xxx.xxx,xx");

        qris.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qris.setForeground(new java.awt.Color(231, 231, 231));
        qris.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/images/qris.png"))); // NOI18N

        pwdLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwdLabel7.setForeground(new java.awt.Color(231, 231, 231));
        pwdLabel7.setText("Password");

        topupButton.setBackground(new java.awt.Color(242, 123, 53));
        topupButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        topupButton.setForeground(new java.awt.Color(231, 231, 231));
        topupButton.setText("Submit");
        topupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confForm7Layout = new javax.swing.GroupLayout(confForm7);
        confForm7.setLayout(confForm7Layout);
        confForm7Layout.setHorizontalGroup(
            confForm7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confForm7Layout.createSequentialGroup()
                .addGroup(confForm7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confForm7Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(topupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(confForm7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(confForm7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pwdLabel7)
                            .addComponent(pwdInput7, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(topupLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(confForm7Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(qris, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        confForm7Layout.setVerticalGroup(
            confForm7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confForm7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(topupLabel)
                .addGap(27, 27, 27)
                .addComponent(totalAmountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalAmount)
                .addGap(18, 18, 18)
                .addComponent(qris, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pwdLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdInput7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(topupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(confForm7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(confForm7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topupButtonActionPerformed
        if(pwdInput7.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Field can't be empty!");
        }else{
            try {
                CashBalance.topUp(usr.getUsername(), jumlah);
                new CashBalance_Investor(usr).setVisible(true);
                this.setVisible(false);
            } catch (Exception ex) {
                Logger.getLogger(TopUpConfirmation_Investor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_topupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopUpConfirmation_Investor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopUpConfirmation_Investor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopUpConfirmation_Investor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopUpConfirmation_Investor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        User usr = null;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TopUpConfirmation_Investor(usr,0).setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TopUpConfirmation_Investor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JButton buyButton1;
    private javax.swing.JButton buyButton2;
    private javax.swing.JButton buyButton3;
    private javax.swing.JButton buyButton4;
    private javax.swing.JButton buyButton5;
    private javax.swing.JButton buyButton6;
    private javax.swing.JPanel confForm;
    private javax.swing.JPanel confForm1;
    private javax.swing.JPanel confForm2;
    private javax.swing.JPanel confForm3;
    private javax.swing.JPanel confForm4;
    private javax.swing.JPanel confForm5;
    private javax.swing.JPanel confForm6;
    private javax.swing.JPanel confForm7;
    private javax.swing.JLabel confLabel;
    private javax.swing.JLabel confLabel1;
    private javax.swing.JLabel confLabel2;
    private javax.swing.JLabel confLabel3;
    private javax.swing.JLabel confLabel4;
    private javax.swing.JLabel confLabel5;
    private javax.swing.JLabel confLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lotLabel;
    private javax.swing.JLabel lotLabel1;
    private javax.swing.JLabel lotLabel2;
    private javax.swing.JLabel lotLabel3;
    private javax.swing.JLabel lotLabel4;
    private javax.swing.JLabel lotLabel5;
    private javax.swing.JLabel lotLabel6;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JLabel priceLabel2;
    private javax.swing.JLabel priceLabel3;
    private javax.swing.JLabel priceLabel4;
    private javax.swing.JLabel priceLabel5;
    private javax.swing.JLabel priceLabel6;
    private javax.swing.JTextField pwdInput;
    private javax.swing.JTextField pwdInput1;
    private javax.swing.JTextField pwdInput2;
    private javax.swing.JTextField pwdInput3;
    private javax.swing.JTextField pwdInput4;
    private javax.swing.JTextField pwdInput5;
    private javax.swing.JTextField pwdInput6;
    private javax.swing.JTextField pwdInput7;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JLabel pwdLabel1;
    private javax.swing.JLabel pwdLabel2;
    private javax.swing.JLabel pwdLabel3;
    private javax.swing.JLabel pwdLabel4;
    private javax.swing.JLabel pwdLabel5;
    private javax.swing.JLabel pwdLabel6;
    private javax.swing.JLabel pwdLabel7;
    private javax.swing.JLabel qris;
    private javax.swing.JButton topupButton;
    private javax.swing.JLabel topupLabel;
    private javax.swing.JLabel totalAmount;
    private javax.swing.JLabel totalAmountLabel;
    private javax.swing.JLabel totalLot;
    private javax.swing.JLabel totalLot1;
    private javax.swing.JLabel totalLot2;
    private javax.swing.JLabel totalLot3;
    private javax.swing.JLabel totalLot4;
    private javax.swing.JLabel totalLot5;
    private javax.swing.JLabel totalLot6;
    private javax.swing.JLabel totalPrice;
    private javax.swing.JLabel totalPrice1;
    private javax.swing.JLabel totalPrice2;
    private javax.swing.JLabel totalPrice3;
    private javax.swing.JLabel totalPrice4;
    private javax.swing.JLabel totalPrice5;
    private javax.swing.JLabel totalPrice6;
    // End of variables declaration//GEN-END:variables
}
